# This is a workflow to run this python script once a year to update the calendar

name: scheduled-yearly-calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 1 *" # runs every year
jobs:
 my_job:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v2 # checkout the repository main to github runner.

   - name: Setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.9 # install the python needed

   - name: Install Requirements
     run: pip install -r requirements.txt

   - name: Execute py script # run the main.py to get the latest data
     run: |
       python main.py

   - name: Setup git config
     run: |
       git config user.name ${{ secrets.USERNAME }}
       git config user.email ${{ secrets.EMAIL }}

   - name: Commit changes
     run: |
       chmod +x ./scripts/commit.sh
       ./scripts/commit.sh